apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mongodb.yaml
  - cluster-manager.yaml
  - network-policy.yaml
configMapGenerator:
  - name: flyt-node-manager-config
    files:
      - node-manager.toml
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: flyt
      app.kubernetes.io/part-of: flyt
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
